#!/bin/bash
# PostToolUse hook: Runs formatter on newly created files.
# Generated by buddyx-forge.

INPUT=$(cat)
if ! command -v jq &>/dev/null; then
  exit 0
fi
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null)
PROJECT_DIR="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"

# Only process source files for this framework
echo "$FILE_PATH" | grep -qE '\.py$' || exit 0

# Resolve to absolute path if relative
if [[ "$FILE_PATH" != /* ]]; then
  FILE_PATH="${PROJECT_DIR}/${FILE_PATH}"
fi

# Only files within this project
[[ "$FILE_PATH" == "$PROJECT_DIR"/* ]] || exit 0

# Only truly new files (not tracked by git)
if git -C "$PROJECT_DIR" ls-files --error-unmatch "$FILE_PATH" &>/dev/null; then
  exit 0
fi

# Run formatter
cd "$PROJECT_DIR" && eval 'black' '"$FILE_PATH"' >/dev/null 2>&1

exit 0
