#!/bin/bash
# UserPromptSubmit hook: Injects current project context into every prompt.
# Generated by buddyx-forge. This script ONLY reads — never modifies code.

PROJECT_DIR="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"

BRANCH=$(git -C "$PROJECT_DIR" branch --show-current 2>/dev/null || echo "unknown")
LAST_COMMIT_MSG=$(git -C "$PROJECT_DIR" log -1 --format="%s" 2>/dev/null || echo "none")
UNSTAGED=$(git -C "$PROJECT_DIR" diff --name-only 2>/dev/null | head -5)
UNSTAGED_COUNT=$(git -C "$PROJECT_DIR" diff --name-only 2>/dev/null | wc -l | tr -d ' ')
STAGED=$(git -C "$PROJECT_DIR" diff --cached --name-only 2>/dev/null | head -5)
STAGED_COUNT=$(git -C "$PROJECT_DIR" diff --cached --name-only 2>/dev/null | wc -l | tr -d ' ')

cat <<EOF
<project-context>
Branch: ${BRANCH}
Last commit: ${LAST_COMMIT_MSG}
Unstaged changes (${UNSTAGED_COUNT} files): $(echo "$UNSTAGED" | tr '\n' ', ' | sed 's/,$//')
Staged changes (${STAGED_COUNT} files): $(echo "$STAGED" | tr '\n' ', ' | sed 's/,$//')
Reminder: Use prompt templates from CLAUDE.md. Ask before guessing. Only touch files in scope.
</project-context>
EOF
